# Create a variable to store the url
@apiUrl = https://back-globe-pocket-latest.onrender.com/api
# @apiUrl = http://localhost:1337/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc1OTIyNzI3MywiZXhwIjoxNzU5MzEzNjczfQ.CubySDWSMKuCvhb6Ph606vayI9WIGBXI_tofwWHR9m8
### création compte
POST {{apiUrl}}/auth/register
Content-Type: application/json
 
{
  "email": "coralierussi@gmail.com",
  "mdp": "4567Test",
  "name": "Coralie"
}

### login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "coralierussi@gmail.com",
  "mdp": "4567Test"
}

### get user info
GET {{apiUrl}}/users

### get user info
GET {{apiUrl}}/users/me
Authorization: Bearer {{token}}

### update user info
PUT {{apiUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Alex",
  "pseudo": "tata",
  "ville": "Grenoble",
  "pays": "France",
  "date_anniversaire": "2025-01-05T00:00:00.000Z",
  "sexe": "Masculin",
  "galerie": [],
  "documents": [],
  "description": "Bye !",
  "cp": 38000,
  "compte_bancaire": 782597234
}

### liste voyages
GET {{apiUrl}}/voyages
Content-Type: application/json

### création voyage
POST {{apiUrl}}/voyages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "destination": "Berlin",
  "date_depart": "2024-08-20T00:00:00.000Z",
  "date_retour": "2025-12-05T00:00:00.000Z",
  "type": "Activites",
  "prix": 2500
}

### Delete voyage
DELETE {{apiUrl}}/voyages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "destination": "Berlin",
  "date_depart": "2024-08-20T00:00:00.000Z",
  "date_retour": "2025-12-05T00:00:00.000Z",
  "type": "Activites",
  "prix": 2500
}

### liste voyages par users
GET {{apiUrl}}/voyages/user
Authorization: Bearer {{token}}

### delete voyage par users
DELETE {{apiUrl}}/voyages/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "destination": "Berlin",
  "date_depart": "2024-08-20T00:00:00.000Z",
  "date_retour": "2025-12-05T00:00:00.000Z",
  "type": "Activites",
  "prix": 2500
}

### liste galerie par users
GET {{apiUrl}}/users/1/photos
Authorization: Bearer {{token}}


### ajouter galerie
PUT {{apiUrl}}/users/1/photos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "galerie": [
    "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN4RJTrFs8g2czpTEQSVxRj3TS8nJo3tYC_pdF_cu3Rbtls5iuPYoDCyhdt1yxLY6WStReFUkJT9B9gECNAJ_1U66gJ7ffFtiVxCb_Y_YC"
  ]
} 

### liste documents par users
GET {{apiUrl}}/users/documents
Authorization: Bearer {{token}}

### ajouter document
PUT {{apiUrl}}/users/documents
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "documents": [
    "https://www.google.com/imgres?q=image&imgurl=https%3A%2F%2Fletsenhance.io%2Fstatic%2F73136da51c245e80edc6ccfe44888a99%2F396e9%2FMainBefore.jpg&imgrefurl=https%3A%2F%2Fletsenhance.io%2Ffr&docid=wlp6cqxXLJM57M&tbnid=g8Tzlw0sX4Aj_M&vet=12ahUKEwj3ppOg0faPAxXdKvsDHcOPG9kQM3oECBwQAA..i&w=1280&h=720&hcb=2&ved=2ahUKEwj3ppOg0faPAxXdKvsDHcOPG9kQM3oECBwQAA"
  ]
} 

### liste rdv
GET {{apiUrl}}/rdv
Authorization: Bearer {{token}}

### ajout rdv
POST {{apiUrl}}/rdv
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date_rdv": "2024-12-15T10:00:00.000Z",
  "heure": "2024-12-15T10:00:00.000Z",
  "titre": "Rendez-vous chez le médecin",
  "mail": "samohtegrofal@mds.com"
}

### suppression rdv
DELETE {{apiUrl}}/rdv
Authorization: Bearer {{token}}

### Update rdv
PUT {{apiUrl}}/rdv
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date_rdv": "2024-12-20T10:00:00.000Z",
  "heure": "2024-12-20T10:00:00.000Z",
  "titre": "Rendez-vous chez le dentiste",
  "mail": "samohtegrofal@mds.com"
}

### liste favoris
GET {{apiUrl}}/user_favoris
Content-Type: application/json
Authorization: Bearer {{token}}

### ajout favoris
POST {{apiUrl}}/user_favoris
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "voyageId": 1
}

### suppression favoris
DELETE {{apiUrl}}/user_favoris/1
Content-Type: application/json
Authorization: Bearer {{token}}