# Create a variable to store the url
@apiUrl = http://localhost:1337/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc1ODI2ODA1NiwiZXhwIjoxNzU4MzU0NDU2fQ.qbSq6y32J9FwsEK9Ijwo4FmTj2k8yzu-BDmkFdVNXlg

### création compte
POST {{apiUrl}}/auth/register
Content-Type: application/json
 
{
  "email": "samohtegrofal@mds.com",
  "mdp": "d467èé%ha4jfx::+/t61fiùra2j9*",
  "name": "toto"
}

### login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "samohtegrofal@mds.com",
  "mdp": "d467èé%ha4jfx::+/t61fiùra2j9*"
}

### get user info
GET {{apiUrl}}/users

### update user info
PUT {{apiUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "samohtegrofal@mds.com",
  "mdp": "d467èé%ha4jfx::+/t61fiùra2j9*",
  "name": "Sam",
  "pseudo": "Sam",
  "ville": "Paris",
  "pays": "France",
  "date_anniversaire": "2025-01-05T00:00:00.000Z",
  "sexe": "Feminin",
  "galerie": [],
  "documents": [],
  "description": "Hello everybody !",
  "cp": 75000,
  "compte_bancaire": 123456789
}

### liste voyages
GET {{apiUrl}}/voyages
Content-Type: application/json

### création voyage
POST {{apiUrl}}/voyages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "destination": "Berlin",
  "date_depart": "2024-08-20T00:00:00.000Z",
  "date_retour": "2025-12-05T00:00:00.000Z",
  "type": "Activites",
  "prix": 2500,
}

# ### Delete voyage
# DELETE {{apiUrl}}/voyages
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#   "destination": "Berlin",
#   "date_depart": "2024-08-20T00:00:00.000Z",
#   "date_retour": "2025-12-05T00:00:00.000Z",
#   "type": "Activites",
#   "prix": 2500,
# }

### liste voyages par users
GET {{apiUrl}}/voyages/user
Authorization: Bearer {{token}}

### delete voyage par users
DELETE {{apiUrl}}/voyages/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "destination": "Berlin",
  "date_depart": "2024-08-20T00:00:00.000Z",
  "date_retour": "2025-12-05T00:00:00.000Z",
  "type": "Activites",
  "prix": 2500,
}

### liste galerie par users
GET {{apiUrl}}/users/1/photos


### ajouter galerie
PUT {{apiUrl}}/users/1/photos
Content-Type: application/json

{
  "galerie": [
    "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN4RJTrFs8g2czpTEQSVxRj3TS8nJo3tYC_pdF_cu3Rbtls5iuPYoDCyhdt1yxLY6WStReFUkJT9B9gECNAJ_1U66gJ7ffFtiVxCb_Y_YC"
  ]
} 

### liste documents par users
GET {{apiUrl}}/users/1/documents
Authorization: Bearer {{token}}

### ajouter document
PUT {{apiUrl}}/users/1/documents
Content-Type: application/json

{
  "documents": [
    "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN4RJTrFs8g2czpTEQSVxRj3TS8nJo3tYC_pdF_cu3Rbtls5iuPYoDCyhdt1yxLY6WStReFUkJT9B9gECNAJ_1U66gJ7ffFtiVxCb_Y_YC"
  ]
} 

### liste rdv
GET {{apiUrl}}/rdv
Authorization: Bearer {{token}}

### ajout rdv
POST {{apiUrl}}/rdv
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date_rdv": "2024-12-15T10:00:00.000Z",
  "heure": "2024-12-15T10:00:00.000Z",
  "titre": "Rendez-vous chez le médecin",
  "mail": "samohtegrofal@mds.com"
}